language: cpp
sudo: false

matrix:
  include:

    # 1/ Linux Clang Builds
#    - os: linux
#      compiler: clang
#      addons: &clang38
#        apt:
#          sources: ['llvm-toolchain-precise', 'ubuntu-toolchain-r-test']
#          packages: ['clang-3.8','binutils']
#      env: CXX_COMPILER='clang++-3.8' C_COMPILER='clang-3.8' AR='clang-ar-3.8' RANLIB='clang-ranlib-3.8'


    # 2/ Linux GCC Builds
    - os: linux
      compiler: gcc
      addons: &gcc49
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9', 'gcc-4.9']
      env: GCCVER='4.9' CXX_COMPILER='g++-4.9' C_COMPILER='gcc-4.9'

#    - os: linux
#      compiler: gcc
#      addons: &gcc5
#        apt:
#          sources: ['ubuntu-toolchain-r-test']
#          packages: ['g++-5', 'gcc-5']
#      env: GCCVER='5' CXX_COMPILER='g++-5' C_COMPILER='gcc-5'

    # 4/ OSX GCC5 Builds
#    - os: osx
#      osx_image: xcode7.3
#      compiler: gcc
#      env: GCCVER='5' CXX_COMPILER='g++-5' C_COMPILER='gcc-5'


    # 5/ Linux GCC5 Coverage build
#    - os: linux
#      compiler: gcc
#      addons: *gcc5
#      env: CXX_COMPILER='g++-5' C_COMPILER='gcc-5' Fortran_COMPILER='gfortran-5' BUILD_TYPE='Debug' COVERAGE=true


before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - export CXX=${CXX_COMPILER}
  - export CC=${C_COMPILER}
  - export AR=gcc-ar-${GCCVER}
  - export RANLIB=gcc-ranlib-${GCCVER}
  - export NM=gcc-nm-${GCCVER}
# - export PATH=$HOME/.local/bin:/usr/local/bin:/usr/bin:$PATH



script : 
  - /bin/sh ./tag.sh
  - autoreconf -vfi 
  - mkdir usr && mkdir usr/local
  - ./configure --enable-nolto --prefix=$PWD/usr/local/ || cat config.log
  - make -j
  - make install
  - tar cvzf $TRAVIS_OS_NAME.tgz usr/
  - mv $TRAVIS_OS_NAME.tgz website/
  - make dist
  - mv ddd*.tar.gz website/ 
  
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: website/
  upload-dir: build/$TRAVIS_BUILD_NUMBER
  on:
    branch: master

  